max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
edition = "2024"
chain_indent = 4
blank_lines_upper_bound = 1
semicolon_newline = true
match_arm_blocks = true
struct_field_align_threshold = 20
fn_args_density = "Compressed"
brace_style = "AlwaysNextLine"
where_style = "AlwaysMultiLine"
format_code_in_doc_comments = false
array_layout = "Vertical"
normalize_comments = true
struct_lit_multiline_style = "ForceMultiLine"
unstable_features = false
format_macro_matchers = true
wrap_comments = true
merge_derives = true
fn_single_line = true
trailing_whitespace = false
