[templates.my-app]
kind = "project"                  # Type of the template: project | monorepo | package
template = "../basic-project"     # Local path to the template source (mutually exclusive with `repo`)

includes = ["src/**"]             # Glob patterns of files to include
excludes = ["target/**"]          # Glob patterns of files to exclude
ignore = [".git"]                 # Files/directories to completely ignore

template_vars = [
  { placeholder = "{{project_name}}", prompt = "Project name", default = "myapp" }
]