[templates.my-app]
kind = "project"                  # Type of the template: project | monorepo | package
template = "./basic-project"     # Local path to the template source (mutually exclusive with `repo`)

includes = ["src/**","package.json"]             # Glob patterns of files to include
excludes = ["target/**","node_modules"]          # Glob patterns of files to exclude

[[template.my-app.template_vars]]
# Required: The placeholder used in the template (e.g., {{project_name}})
placeholder = "{{project_name}}"

# Optional: A message shown to the user when prompting for input
prompt = "Please input your new project name"

# Optional: A default value to use if no input is provided
default = "new_project"

# Optional: Limit replacement to specific files only
# Supports regex by prefixing with `regex:`
includes_paths = [
  "package.json",
]